{% set name = "esutil" %}
{% set version = "0.6.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 92fdd9ee71d2abe8e595b3d62457f7002c584d8e7be2d23097744f05d306d01c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python

test:
  imports:
    - esutil
    - esutil.htm
    - esutil.stat
    - esutil.cosmology

about:
  home: https://github.com/esheldon/esutil
  license: GPL-2.0-only
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: |
    A python package including a wide variety of utilities, focused primarily
    on numerical python, statistics, and file input/output. Includes
    specialized tools for astronomers.

extra:
  recipe-maintainers:
    - beckermr
