{% set name = "esutil" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 92116bea978abfac4e5b0d682e83e6e0770b8014df0ab38bd8fb929c0b6ed227

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - esutil
  commands:
    - python -c "import esutil; esutil.test()"

about:
  home: https://github.com/esheldon/esutil
  license: GPLv2
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: |
    A python package including a wide variety of utilities, focused primarily
    on numerical python, statistics, and file input/output. Includes
    specialized tools for astronomers.

extra:
  recipe-maintainers:
    - beckermr
