schema_version: 1

context:
  version: "0.6.17"

package:
  name: esutil
  version: ${{ version }}

source:
  url: https://github.com/esheldon/esutil/archive/${{ version }}.tar.gz
  sha256: 59ed1b93db18c71c5483f12938b7bb76e5fabccfdf0f7371565f2ddce7008587

build:
  number: 0
  script:
    - if: linux
      then: export CFLAGS="${CFLAGS} -Wno-incompatible-pointer-types"
    - ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python

tests:
  - python:
      imports:
        - esutil
        - esutil.htm
        - esutil.stat
        - esutil.cosmology
      pip_check: false

about:
  homepage: https://github.com/esheldon/esutil
  license: GPL-2.0-only
  license_file: LICENSE
  summary: |
    A python package including a wide variety of utilities, focused primarily
    on numerical python, statistics, and file input/output. Includes
    specialized tools for astronomers.

extra:
  recipe-maintainers:
    - beckermr
