appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: r3sI3EHGxWXvxPFBYWSVd2Ekh/W7Zy++4iic7tZ9p0zskeoTSgtyqftnjHj5HhrNQ82C2FpmCB66O7tCyFack9f8cRddIqYPeDvlporGDR4zS5qb6hrP07CsGcuyrZymmOW3FL9NlJuUfFnROv1lVLRc2rkjEpxrfE67e1moPtl/XUpyZOtl/hzANWZPccvb4GnmjgIJsobNmbVUUXzZFJw+FvBIk6HKhsDeIn8PQqbIP2PR8nhHGb0Gq0OTROTTym4VL/oy9JZ8O4orl6ry5ukeGvK42SBKV2qlgLd/YcZ1zK0VsAVJwFMfkPaOY5aPZue1wTu30NGh9MHzz8Cp6I9rijh92Ex+OSMA5tOKK1dHofrH2Ice4SHkUp84kpc6lWV1KFvf/4t53ysZEQI+cw7+bu5G//EsFGGHYbIelkF0PSN085YX9i7dETUEh6Zw0ZP9chS4/0SWCX+KUOuuW/WyVHVEI1OSr3ftxgzPRZ8YN5s6qQgQjlIIMbvd2itq4yFY3AvIEaq7trrdaao71CPEiwO6Bmf9UEnN22nO8jbuVXerZxzSXhJieob6asKpedjpxwppg9lwriyyUXx77j/nJ4N9xFJR8P1AlhTJNvEPZfE4zFB0CcsFLYlf5JnsgQBRzcuu5TS6N3ouwIgEJMVGKFmmeRZsO95FdPTi6Wg=}
conda_forge_output_validation: true
